CREATE TABLE plist ( idnum SMALLINT UNSIGNED, nname VARCHAR(45), ci BIGINT, CONSTRAINT pkplist PRIMARY KEY(idnum));



CREATE TABLE transaccion (num INT AUTO_INCREMENT, hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP, idnum SMALLINT UNSIGNED,
 weight DECIMAL(6,2),
 price DECIMAL(6,2), oper SMALLINT UNSIGNED, t_stamp DATETIME, CONSTRAINT pktransaccion PRIMARY KEY(num),

 CONSTRAINT fktransaccion FOREIGN KEY(idnum) REFERENCES plist(idnum));
    


CREATE TABLE cost (hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP, rate DECIMAL(6,2))